# Generated by Django 5.1.4 on 2026-06-16 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('stato', models.CharField(choices=[('bozza_in_corso', 'Bozza in corso'), ('analizzato', 'Analizzato'), ('bozza_generata', 'Bozza generata'), ('in_revisione', "In revisione (interna all'utente)"), ('completato', 'Completato')], default='bozza_in_corso', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavori', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SezioneDocumenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('generici', 'Documenti generici'), ('attore', "Fascicolo dell'attore"), ('convenuto', 'Fascicolo del convenuto/ricorrente')], max_length=16)),
                ('lavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sezioni', to='casi.lavoro')),
            ],
            options={
                'unique_together': {('lavoro', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documenti/%Y/%m/')),
                ('tipo_rilevato', models.CharField(blank=True, max_length=64)),
                ('metodo_estrazione', models.CharField(blank=True, choices=[('pdf_nativo', 'PDF nativo (testo selezionabile)'), ('glm_ocr', 'GLM-OCR (scansione/immagine/manoscritto)')], max_length=16)),
                ('testo_estratto', models.TextField(blank=True)),
                ('ocr_confidenza', models.FloatField(blank=True, null=True)),
                ('flag_bassa_confidenza', models.BooleanField(default=False)),
                ('passaggi_incerti', models.JSONField(blank=True, default=list)),
                ('testo_pseudonimizzato', models.TextField(blank=True)),
                ('mappa_entita', models.JSONField(blank=True, default=dict)),
                ('stato_accettazione', models.CharField(choices=[('da_verificare', 'Da verificare'), ('verificato', 'Verificato'), ('accettato_senza_verifica', 'Accettato senza verifica')], default='da_verificare', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='casi.sezionedocumenti')),
            ],
        ),
    ]
