# Generated by Django 5.1.4 on 2026-06-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='errore_estrazione',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='stato_estrazione',
            field=models.CharField(choices=[('in_attesa', 'In attesa'), ('in_corso', 'In corso'), ('completato', 'Completato'), ('errore', 'Errore')], default='in_attesa', max_length=16),
        ),
    ]
