# Generated by Django 5.1.4 on 2026-06-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casi', '0002_documento_errore_estrazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='pseudonimizzato',
            field=models.BooleanField(default=False),
        ),
    ]
