# Generated by Django 5.1.4 on 2026-06-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casi', '0003_documento_pseudonimizzato'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavoro',
            name='analisi_errore',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lavoro',
            name='analisi_stato',
            field=models.CharField(choices=[('in_attesa', 'In attesa'), ('in_corso', 'In corso'), ('completata', 'Completata'), ('errore', 'Errore')], default='in_attesa', max_length=16),
        ),
    ]
