# Generated by Django 5.1.4 on 2026-06-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casi', '0006_lavoro_ricerca_errore_lavoro_ricerca_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='errore_anonimizzazione',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='stato_anonimizzazione',
            field=models.CharField(choices=[('in_attesa', 'In attesa'), ('in_corso', 'In corso'), ('completata', 'Completata'), ('errore', 'Errore')], default='in_attesa', max_length=16),
        ),
        migrations.AddField(
            model_name='lavoro',
            name='mappa_entita',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
