# Generated by Django 5.1.4 on 2026-06-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casi', '0007_documento_errore_anonimizzazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavoro',
            name='modello_testo',
            field=models.TextField(blank=True),
        ),
    ]
