# Generated by Django 5.1.4 on 2026-06-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casi', '0008_lavoro_modello_testo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavoro',
            name='analisi_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lavoro',
            name='approfondimento_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lavoro',
            name='ricerca_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
