# Generated by Django 5.1.4 on 2026-06-28 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casi', '0010_lavoro_progress_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nome_logico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documento',
            name='ordine',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lavoro',
            name='assegnato_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavori_assegnati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lavoro',
            name='revisore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavori_da_revisionare', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lavoro',
            name='stato_revisione',
            field=models.CharField(choices=[('da_rivedere', 'Da rivedere'), ('in_revisione', 'In revisione'), ('validato', 'Validato'), ('esportato', 'Esportato')], default='da_rivedere', max_length=24),
        ),
    ]
