# Generated by Django 5.1.4 on 2026-06-16 19:12

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpus', '0001_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('fonte', models.CharField(blank=True, max_length=512)),
                ('testo', models.TextField()),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('in_corso', 'Indicizzazione in corso'), ('completato', 'Completato'), ('errore', 'Errore')], default='in_attesa', max_length=16)),
                ('errore', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrammentoCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('testo', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frammenti', to='corpus.documentocorpus')),
            ],
            options={
                'ordering': ['documento_id', 'ordine'],
            },
        ),
    ]
