# Generated by Django 5.1.4 on 2026-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocorpus',
            name='categoria',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
