from django.urls import path

from .views import (
    AnnullaAnalisiView,
    ApprofondisciView,
    ApprofondisciRichiestaView,
    ApplicaAzioneLacunaView,
    AvviaAnalisiView,
    AvviaRicercaView,
    BozzaView,
    CommentiEditorView,
    CommentoEditorUpdateView,
    EsportaAuditDocxView,
    EsportaDocxView,
    EventiDecisioneListView,
    FattoProcessualeUpdateView,
    FonteRichiestaView,
    MatriceLavoroView,
    RicercaManualeView,
    RedTeamFascicoloView,
    RevisioneFascicoloView,
    RichiestaUpdateView,
    RichiesteListView,
    SpuntiListView,
    TemplateProvvedimentiView,
)

urlpatterns = [
    path("lavori/<int:lavoro_id>/analizza/", AvviaAnalisiView.as_view(), name="analizza"),
    path("lavori/<int:lavoro_id>/annulla/", AnnullaAnalisiView.as_view(), name="annulla"),
    path("lavori/<int:lavoro_id>/approfondisci/", ApprofondisciView.as_view(), name="approfondisci"),
    path("lavori/<int:lavoro_id>/richieste/", RichiesteListView.as_view(), name="richieste"),
    path("lavori/<int:lavoro_id>/matrice/", MatriceLavoroView.as_view(), name="matrice"),
    path("lavori/<int:lavoro_id>/eventi/", EventiDecisioneListView.as_view(), name="eventi-decisione"),
    path("lavori/<int:lavoro_id>/red-team/", RedTeamFascicoloView.as_view(), name="red-team"),
    path("lavori/<int:lavoro_id>/revisione/", RevisioneFascicoloView.as_view(), name="revisione"),
    path("lavori/<int:lavoro_id>/azioni/", ApplicaAzioneLacunaView.as_view(), name="azioni-lacune"),
    path("lavori/<int:lavoro_id>/commenti/", CommentiEditorView.as_view(), name="commenti-editor"),
    path("commenti/<int:pk>/", CommentoEditorUpdateView.as_view(), name="commento-editor-update"),
    path("richieste/<int:pk>/", RichiestaUpdateView.as_view(), name="richiesta-update"),
    path("richieste/<int:pk>/approfondisci/", ApprofondisciRichiestaView.as_view(), name="richiesta-approfondisci"),
    path("richieste/<int:pk>/fonti/", FonteRichiestaView.as_view(), name="richiesta-fonti"),
    path("matrice/<int:pk>/", FattoProcessualeUpdateView.as_view(), name="matrice-update"),
    path("lavori/<int:lavoro_id>/bozza/", BozzaView.as_view(), name="bozza"),
    path("lavori/<int:lavoro_id>/esporta/", EsportaDocxView.as_view(), name="esporta"),
    path("lavori/<int:lavoro_id>/audit/", EsportaAuditDocxView.as_view(), name="audit"),
    path("lavori/<int:lavoro_id>/ricerca/", AvviaRicercaView.as_view(), name="ricerca"),
    path("lavori/<int:lavoro_id>/ricerca/manuale/", RicercaManualeView.as_view(), name="ricerca-manuale"),
    path("lavori/<int:lavoro_id>/spunti/", SpuntiListView.as_view(), name="spunti"),
    path("template-provvedimenti/", TemplateProvvedimentiView.as_view(), name="template-provvedimenti"),
]
