# Generated by Django 5.1.4 on 2026-06-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bozza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_fatto', models.TextField(blank=True)),
                ('contenuto_per_richiesta', models.JSONField(blank=True, default=dict)),
                ('versione', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lavoro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bozza', to='casi.lavoro')),
            ],
        ),
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte_richiedente', models.CharField(choices=[('attore', 'Attore'), ('convenuto', 'Convenuto/ricorrente')], max_length=16)),
                ('testo', models.TextField()),
                ('stato', models.CharField(choices=[('da_analizzare', 'Da analizzare'), ('analizzata', 'Analizzata')], default='da_analizzare', max_length=16)),
                ('onere_probatorio', models.TextField(blank=True)),
                ('non_contestazioni', models.JSONField(blank=True, default=list)),
                ('quesiti_aperti', models.JSONField(blank=True, default=list)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('allegati_collegati', models.ManyToManyField(blank=True, related_name='richieste', to='casi.documento')),
                ('lavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste', to='casi.lavoro')),
            ],
            options={
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
