# Generated by Django 5.1.4 on 2026-06-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisi', '0001_initial'),
        ('casi', '0006_lavoro_ricerca_errore_lavoro_ricerca_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiesta',
            name='stato',
            field=models.CharField(choices=[('da_analizzare', 'Da analizzare'), ('analizzata', 'Analizzata'), ('approfondita', 'Approfondita (in diritto)')], default='da_analizzare', max_length=16),
        ),
        migrations.CreateModel(
            name='SpuntoRicerca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_pseudonimizzata', models.CharField(blank=True, max_length=512)),
                ('argomento', models.CharField(blank=True, max_length=255)),
                ('sintesi', models.TextField()),
                ('suggerimento', models.TextField(blank=True)),
                ('fonte', models.URLField(blank=True)),
                ('origine', models.CharField(choices=[('web', 'Ricerca web'), ('manuale', 'Inserito manualmente')], default='web', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spunti', to='casi.lavoro')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
