# Generated by Django 5.1.4 on 2026-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisi', '0002_alter_richiesta_stato_spuntoricerca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spuntoricerca',
            name='fonte',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
