# Generated by Django 5.1.4 on 2026-06-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisi', '0003_alter_spuntoricerca_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='bozza',
            name='pqm',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='motivazione',
            field=models.TextField(blank=True),
        ),
    ]
