# Generated by Django 5.1.4 on 2026-06-28 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisi', '0008_contraddittorio_eventodecisionale'),
        ('casi', '0010_lavoro_progress_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventodecisionale',
            name='tipo',
            field=models.CharField(choices=[('matrice_aggiornata', 'Matrice aggiornata'), ('motivazione_aggiornata', 'Motivazione aggiornata'), ('bozza_aggiornata', 'Bozza aggiornata'), ('commento_editor', 'Commento editor'), ('fonte_aggiornata', 'Fonte aggiornata'), ('azione_lacuna', 'Azione su lacuna'), ('audit_esportato', 'Audit esportato'), ('red_team_eseguito', 'Red team eseguito')], max_length=32),
        ),
        migrations.CreateModel(
            name='CommentoEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezione', models.CharField(choices=[('in_fatto', 'In fatto'), ('in_diritto', 'In diritto'), ('pqm', 'P.Q.M.'), ('fonte', 'Fonte'), ('privacy', 'Privacy'), ('generale', 'Generale')], default='generale', max_length=24)),
                ('riferimento_id', models.PositiveIntegerField(blank=True, null=True)),
                ('testo', models.TextField()),
                ('risolto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti_editor', to='casi.lavoro')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commenti_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
