# Generated by Django 5.1.4 on 2026-06-18 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casi', '0007_documento_errore_anonimizzazione_and_more'),
        ('corpus', '0003_documentocorpus_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrafoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_corso', models.BooleanField(default=False)),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('concetto', 'Concetto/istituto'), ('riferimento', 'Riferimento normativo'), ('caso', 'Fascicolo/caso')], default='concetto', max_length=16)),
                ('etichetta', models.CharField(max_length=255)),
                ('chiave', models.CharField(max_length=255, unique=True)),
                ('sintesi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodi', to='corpus.documentocorpus')),
                ('lavoro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodi_grafo', to='casi.lavoro')),
            ],
            options={
                'ordering': ['etichetta'],
            },
        ),
        migrations.CreateModel(
            name='Arco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cita', 'Cita'), ('correlato', 'Correlato'), ('in_contrasto', 'In contrasto'), ('applica', 'Applica')], default='correlato', max_length=16)),
                ('peso', models.FloatField(default=1.0)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archi_entranti', to='conoscenza.nodo')),
                ('da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archi_uscenti', to='conoscenza.nodo')),
            ],
            options={
                'unique_together': {('da', 'a', 'tipo')},
            },
        ),
    ]
